-- Create Profiles Table
-- This table stores public user data and links to the auth.users table.
CREATE TABLE public.profiles (
  id UUID NOT NULL,
  updated_at TIMESTAMPTZ,
  email VARCHAR(255),
  api_key TEXT,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create History Table
-- This table stores the generation history for each user.
CREATE TABLE public.history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id UUID,
  prompt TEXT,
  video_url TEXT,
  status VARCHAR(255),
  CONSTRAINT history_pkey PRIMARY KEY (id),
  CONSTRAINT history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;

-- Create Policies for Profiles
-- Allow users to view their own profile.
CREATE POLICY "Enable read access for users based on user_id" ON public.profiles FOR SELECT USING (auth.uid() = id);
-- Allow users to update their own profile.
CREATE POLICY "Enable update for users based on user_id" ON public.profiles FOR UPDATE USING (auth.uid() = id);
-- **NEW:** Allow users to insert their own profile.
CREATE POLICY "Enable insert for users based on user_id" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);


-- Create Policies for History
-- Allow users to view their own history.
CREATE POLICY "Enable read access for users based on user_id" ON public.history FOR SELECT USING (auth.uid() = user_id);
-- Allow users to insert their own history.
CREATE POLICY "Enable insert for users based on user_id" ON public.history FOR INSERT WITH CHECK (auth.uid() = user_id);