-- This script is idempotent, meaning it can be run multiple times safely.
-- It will first clean up any existing objects before creating them.

-- 1. Clean up old objects if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.history;
DROP TABLE IF EXISTS public.profiles;

-- 2. Create Profiles Table
-- This table stores public user data and links to the auth.users table.
CREATE TABLE public.profiles (
  id UUID NOT NULL,
  updated_at TIMESTAMPTZ,
  email VARCHAR(255),
  api_key TEXT,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Create History Table
-- This table stores the generation history for each user.
CREATE TABLE public.history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id UUID,
  prompt TEXT,
  video_url TEXT,
  status VARCHAR(255),
  CONSTRAINT history_pkey PRIMARY KEY (id),
  CONSTRAINT history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Rules) for the Tables
-- Profiles Policies
CREATE POLICY "Enable read access for users based on user_id" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Enable update for users based on user_id" ON public.profiles FOR UPDATE USING (auth.uid() = id);
-- History Policies
CREATE POLICY "Enable read access for users based on user_id" ON public.history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Enable insert for users based on user_id" ON public.history FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. The Trigger Function to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. The Trigger that calls the function
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();