# -*- coding: utf-8 -*-
"""Veo Video Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYw0YjAZ1s5Zege_1PjXpwZrff7xnQtC
"""

import os
import time
from typing import Optional, List
from google import genai
from google.genai import types

def generate_veo_video(
    image_path: str,
    user_prompt: str = "",
    project_id: Optional[str] = None,
    location: str = "us-central1",
    video_model: str = "veo-3.1-fast-generate-001",
    gemini_model: str = "gemini-2.5-flash",
    use_gemini_enhancement: bool = True,
    camera_motion: str = "None",
    subject_animation: str = "None",
    environmental_animation: str = "None",
    dialogue: str = "",
    sound_effects: str = "",
    duration_seconds: int = 4,
    aspect_ratio: str = "16:9",
    resolution: str = "720p",
    enhance_prompt: bool = False,
    generate_audio: bool = False,
    output_filename: str = "output_video.mp4"
) -> bytes:
    """
    Generates a video using Google Veo.
    Can optionally enhance the prompt using Gemini before sending to Veo.

    Returns:
        bytes: The raw video data.
    """

    # 1. Setup Client
    pid = project_id or os.environ.get("GOOGLE_CLOUD_PROJECT")
    if not pid:
        raise ValueError("Project ID must be provided or set in GOOGLE_CLOUD_PROJECT environment variable.")

    client = genai.Client(vertexai=True, project=pid, location=location)

    # 2. Build Keywords for Prompting
    keywords = []
    optional_keywords = [
        camera_motion,
        subject_animation,
        environmental_animation,
        sound_effects,
    ]
    for kw in optional_keywords:
        if kw and kw.lower() != "none":
            keywords.append(kw)
    if dialogue:
        keywords.append(dialogue)

    formatted_keywords = ", ".join(keywords)

    with open(image_path, "rb") as f:
        image_bytes = f.read()

    # 3. Prompt Preparation
    final_prompt = user_prompt

    if use_gemini_enhancement:
        print("Enhancing prompt with Gemini...")
        gemini_system_instruction = (
            "You are an expert prompt engineer for Google's Veo model. "
            "Analyze the provided image and user prompt to generate a single, cohesive, "
            "and cinematic prompt. Integrate requested motion and audio effects. "
            "Output ONLY the final prompt text."
        )

        gemini_user_query = f"Mandatory Keywords: {formatted_keywords}. User Prompt: {user_prompt}"

        gemini_response = client.models.generate_content(
            model=gemini_model,
            contents=[
                types.Part.from_bytes(data=image_bytes, mime_type="image/png"),
                gemini_user_query
            ],
            config=types.GenerateContentConfig(system_instruction=gemini_system_instruction)
        )
        final_prompt = gemini_response.text
        print(f"Gemini Enhanced Prompt: {final_prompt}")
    else:
        # If not using Gemini, manually append keywords to the prompt if they exist
        if formatted_keywords:
            final_prompt = f"{user_prompt}. Cinematic style. Keywords: {formatted_keywords}."
        print(f"Using direct prompt: {final_prompt}")

    # 4. Generate Video with Veo
    print("Starting Veo video generation...")
    operation = client.models.generate_videos(
        model=video_model,
        prompt=final_prompt,
        image=types.Image.from_bytes(data=image_bytes, mime_type="image/png"),
        config=types.GenerateVideosConfig(
            aspect_ratio=aspect_ratio,
            number_of_videos=1,
            duration_seconds=duration_seconds,
            resolution=resolution,
            person_generation="allow_adult",
            enhance_prompt=enhance_prompt,
            generate_audio=generate_audio,
        ),
    )

    # 5. Poll for completion
    while not operation.done:
        print("Waiting for video generation... (checking in 15s)")
        time.sleep(15)
        operation = client.operations.get(operation)

    if operation.result and operation.result.generated_videos:
        video_data = operation.result.generated_videos[0].video.video_bytes

        # Save to disk if filename is provided
        if output_filename:
            with open(output_filename, "wb") as f:
                f.write(video_data)
            print(f"Video saved to {output_filename}")

        return video_data
    else:
        raise RuntimeError("Video generation failed or returned no results.")

if __name__ == "__main__":
    # Example usage: skipping Gemini enhancement
    try:
        generate_veo_video(
            image_path="input_image.png",
            user_prompt="A robot playing chess",
            use_gemini_enhancement=False,
            camera_motion="Zoom (In)",
            output_filename="manual_prompt_video.mp4"
        )
    except Exception as e:
        print(f"Error: {e}")